#!/bin/bash

echo ""
printf "List Files : "; ls;
read -p "List Email : " listnya;

# CLEANING LIST 
sed -i 's/\r//' $listnya
cat $listnya | grep -Eo '[[:alnum:]+\.\_\-]*@[[:alnum:]+\.\_\-]*' | sort | uniq -i >> ${listnya}_tmp
mv ${listnya}_tmp ${listnya}


# BIKIN FOLDER

if [[ ! -d result ]]; then
	mkdir result
fi

# JALANKEUN

# HOTMAIL
for hasilHotmail in $(cat $listnya | grep -Eo "\b[[:alnum:]+\.\_\-]*@hotmail+\.[a-zA-Z0-9.-]+\b"); do
	echo "$hasilHotmail" >> result/hotmail.txt
done
echo "[+] Hotmail Total : $(cat result/hotmail.txt | wc -l)"

# OUTLOOK
for hasiloutlook in $(cat $listnya | grep -Eo "\b[[:alnum:]+\.\_\-]*@outlook+\.[a-zA-Z0-9.-]+\b"); do
	echo "$hasiloutlook" >> result/outlook.txt
done
echo "[+] Outlook Total : $(cat result/outlook.txt | wc -l)"

# LIVE
for hasillive in $(cat $listnya | grep -Eo "\b[[:alnum:]+\.\_\-]*@live+\.[a-zA-Z0-9.-]+\b"); do
	echo "$hasillive" >> result/live.txt
done
echo "[+] Live Mail Total : $(cat result/live.txt | wc -l)"

# GMAIL
ngitungGMAIL=0
for hasilGMAIL in $(cat $listnya | grep -Eo "\b[[:alnum:]+\.\_\-]*@gmail+\.[a-zA-Z0-9.-]+\b"); do
	echo "$hasilGMAIL" >> result/gmail.txt
done
echo "[+] Gmail Total : $(cat result/gmail.txt | wc -l)"

# GOOGLEMAIL
for hasilGOOGLEMAIL in $(cat $listnya | grep -Eo "\b[[:alnum:]+\.\_\-]*@googlemail+\.[a-zA-Z0-9.-]+\b"); do
	echo "$hasilGOOGLEMAIL" >> result/googlemail.txt
done
echo "[+] Googlemail Total : $(cat result/googlemail.txt | wc -l)"

# YAHOO
for hasilYAHOO in $(cat $listnya | grep -Eo "\b[[:alnum:]+\.\_\-]*@yahoo+\.[a-zA-Z0-9.-]+\b"); do
	echo "$hasilYAHOO" >> result/yahoo.txt
done
echo "[+] Yahoo Total : $(cat result/yahoo.txt | wc -l)"

# YMAIL
for hasilYMAIL in $(cat $listnya | grep -Eo "\b[[:alnum:]+\.\_\-]*@ymail+\.[a-zA-Z0-9.-]+\b"); do
	echo "$hasilYMAIL" >> result/ymail.txt
done
echo "[+] Ymail Total : $(cat result/ymail.txt | wc -l)"

# AOL
for hasilAOL in $(cat $listnya | grep -Eo "\b[[:alnum:]+\.\_\-]*@aol+\.[a-zA-Z0-9.-]+\b"); do
	echo "$hasilAOL" >> result/aol.txt
done
echo "[+] Aol Total : $(cat result/aol.txt | wc -l)"

# YANDEX
for hasilYANDEX in $(cat $listnya | grep -Eo "\b[[:alnum:]+\.\_\-]*@yandex+\.[a-zA-Z0-9.-]+\b"); do
	echo "$hasilYANDEX" >> result/yandex.txt
done
echo "[+] Yandex Total : $(cat result/yandex.txt | wc -l)"

# GMX
for hasilGMX in $(cat $listnya | grep -Eo "\b[[:alnum:]+\.\_\-]*@gmx+\.[a-zA-Z0-9.-]+\b"); do
	echo "$hasilGMX" >> result/gmx.txt
done
echo "[+] Gmx Total : $(cat result/gmx.txt | wc -l)"

# MAIL.RU
for hasilMAILRU in $(cat $listnya | grep -Eo "\b[[:alnum:]+\.\_\-]*@mail+\.[a-zA-Z0-9.-]+\b"); do
	echo "$hasilMAILRU" >> result/mailru.txt
done
echo "[+] Mail.ru Total : $(cat result/mailru.txt | wc -l)"

# Other
for hasilOTHER in $(cat $listnya | grep -v "@gmx." | grep -v "@mail." | grep -v "@hotmail." | grep -v "@outlook." | grep -v "@live." | grep -v "@yahoo." | grep -v "@ymail." | grep -v "@gmail." | grep -v "@googlemail." | grep -v "@aol." | grep -v "@yandex."); do
	echo "$hasilOTHER" >> result/other.txt
done
echo "[+] Other Total : $(cat result/other.txt | wc -l)"

read -p "Compress result? [y/n]: " kompres;
ngecilin=$(echo $kompres | tr '[:upper:]' '[:lower:]')
if [[ $ngecilin == "y" ]]; then
	zip -q -r result.zip result
	echo "\nALL DONE\n"
else
	echo "\nALL DONE\n"
	exit 1;
fi
